"""add is_confirmed to user

Revision ID: 0929350a7957
Revises: dfc712eb4acd
Create Date: 2024-08-24 17:22:34.602924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0929350a7957'
down_revision: Union[str, None] = 'dfc712eb4acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_confirmed')
    # ### end Alembic commands ###
