"""deleted test column

Revision ID: 2e18b8d0237a
Revises: 79779b2802cf
Create Date: 2024-08-01 15:02:27.783747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e18b8d0237a'
down_revision: Union[str, None] = '79779b2802cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('nickname', sa.VARCHAR(length=64), server_default=sa.text("'NICKNAME'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
