"""test column adding

Revision ID: 79779b2802cf
Revises: bc54af052d73
Create Date: 2024-08-01 15:00:28.510921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79779b2802cf'
down_revision: Union[str, None] = 'bc54af052d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('nickname', sa.String(length=64), nullable=False, server_default="NICKNAME"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'nickname')
    # ### end Alembic commands ###
