"""added role to User

Revision ID: bc54af052d73
Revises: 8b2bc820752c
Create Date: 2024-08-01 14:01:18.914669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc54af052d73'
down_revision: Union[str, None] = '8b2bc820752c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE roleenum AS ENUM ('SUPERUSER', 'ADMIN', 'USER')")
    op.add_column('User', sa.Column(
        'role',
        sa.Enum('SUPERUSER', 'ADMIN', 'USER', name='roleenum'),
        nullable=False,
        server_default="USER"
    ))
    op.create_unique_constraint(None, 'User', ['username'])
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'role')
    # ### end Alembic commands ###
